project:
  type: website

website:
  title: "Kyle Grgecic's Data Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kylegrg/comm3180_S26_Blog
format:
  html:
    theme: pulse
    css: styles.css

execute:
  freeze: auto


